apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
  - name: maven-repo
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      Default: ["package"]
    resources:
    - name: source
      targetPath: /
      type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      Command: ["/usr/bin/mvn"]
      args:
        - "$(inputs.params.GOALS)"
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)